apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    control-plane: gitops-operator
  name: openshift-gitops-operator-metrics-monitor
  namespace: openshift-gitops-operator
spec:
  endpoints:
  - bearerTokenSecret:
      name: gitops-monitor-token
      key: token
    interval: 30s
    path: /metrics
    port: metrics
    scheme: https
    tlsConfig:
      ca:
        configMap:
          name: openshift-service-ca.crt
          key: service-ca.crt
      serverName: openshift-gitops-operator-metrics-service.openshift-gitops-operator.svc
  selector:
    matchLabels:
      control-plane: gitops-operator
