apiVersion: v1
kind: Secret
metadata:
  name: gitops-monitor-token
  namespace: openshift-gitops-operator
  annotations:
    kubernetes.io/service-account.name: openshift-gitops-operator-controller-manager
type: kubernetes.io/service-account-token
