apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: workload-pool
  namespace: metallb-system
spec:
  addresses:
  - 172.16.130.40-172.16.130.99
  autoAssign: true
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: workload-adv
  namespace: metallb-system
spec:
  ipAddressPools:
  - workload-pool
  interfaces:
  - br130