apiVersion: v1
kind: Secret
metadata:
  name: metallb-monitor-token
  namespace: metallb-system
  annotations:
    kubernetes.io/service-account.name: controller
type: kubernetes.io/service-account-token
