apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitops-test-pvc
  namespace: default
spec:
  storageClassName: truenas-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: Pod
metadata:
  name: gitops-test-pod
  namespace: default
spec:
  containers:
  - name: test
    image: alpine:latest
    command: ["/bin/sh", "-c", "echo 'GitOps Migration Successful' > /mnt/nfs/gitops-check.txt && sleep 3600"]
    volumeMounts:
    - mountPath: "/mnt/nfs"
      name: vol
  volumes:
  - name: vol
    persistentVolumeClaim:
      claimName: gitops-test-pvc
