apiVersion: apps/v1
kind: Deployment
metadata:
  name: bazarr
  namespace: media-stack
  labels:
    app: bazarr
    zone: zone2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bazarr
  template:
    metadata:
      labels:
        app: bazarr
        zone: zone2
    spec:
      serviceAccountName: managers
      initContainers:
      - name: init-dirs
        image: docker.io/alpine:latest
        command: ["/bin/sh", "-c", "mkdir -p /mnt/media/zurg /mnt/media/torbox"]
        volumeMounts:
        - name: media-storage
          mountPath: /mnt/media
      containers:
      # Sidecar: Mount Zurg
      - name: rclone-zurg
        image: docker.io/rclone/rclone:latest
        securityContext:
          privileged: true
        args:
        - "mount"
        - "zurg:"
        - "/mnt/media/zurg"
        - "--config=/config/rclone/rclone.conf"
        - "--allow-other"
        - "--vfs-cache-mode=full"
        volumeMounts:
        - name: media-storage
          mountPath: /mnt/media
          mountPropagation: Bidirectional
        - name: rclone-zurg-config
          mountPath: /config/rclone
          readOnly: true
      # Sidecar: Mount TorBox
      - name: rclone-torbox
        image: docker.io/rclone/rclone:latest
        securityContext:
          privileged: true
        args:
        - "mount"
        - "torbox:"
        - "/mnt/media/torbox"
        - "--config=/config/rclone/rclone.conf"
        - "--allow-other"
        - "--vfs-cache-mode=full"
        volumeMounts:
        - name: media-storage
          mountPath: /mnt/media
          mountPropagation: Bidirectional
        - name: rclone-config
          mountPath: /config/rclone
          readOnly: true
      # Main: Bazarr
      - name: bazarr
        image: lscr.io/linuxserver/bazarr:latest
        securityContext:
          privileged: true
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "Etc/UTC"
        ports:
        - containerPort: 6767
          name: http
        volumeMounts:
        - name: media-storage
          mountPath: /config
          subPath: config/bazarr
        - name: media-storage
          mountPath: /mnt/media
          mountPropagation: HostToContainer
        readinessProbe:
          tcpSocket:
            port: 6767
          initialDelaySeconds: 20
          periodSeconds: 10
      volumes:
      - name: media-storage
        persistentVolumeClaim:
          claimName: media-library-pvc
      - name: rclone-zurg-config
        secret:
          secretName: rclone-zurg-config
      - name: rclone-config
        secret:
          secretName: rclone-config
---
apiVersion: v1
kind: Service
metadata:
  name: bazarr
  namespace: media-stack
spec:
  selector:
    app: bazarr
  ports:
    - protocol: TCP
      port: 6767
      targetPort: 6767
  type: ClusterIP