apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowlarr
  namespace: media-stack
  labels:
    app: prowlarr
    zone: zone2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prowlarr
  template:
    metadata:
      labels:
        app: prowlarr
        zone: zone2
    spec:
      serviceAccountName: managers
      containers:
      # Main: Prowlarr
      - name: prowlarr
        image: lscr.io/linuxserver/prowlarr:latest
        securityContext:
          privileged: true
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "Etc/UTC"
        ports:
        - containerPort: 9696
          name: http
        volumeMounts:
        - name: media-storage
          mountPath: /config
          subPath: config/prowlarr
        readinessProbe:
          tcpSocket:
            port: 9696
          initialDelaySeconds: 20
          periodSeconds: 10
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
      volumes:
      - name: media-storage
        persistentVolumeClaim:
          claimName: media-library-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: prowlarr
  namespace: media-stack
spec:
  selector:
    app: prowlarr
  ports:
    - protocol: TCP
      port: 9696
      targetPort: 9696
  type: ClusterIP
