apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-monitoring
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/sigtom/wow-ocp.git
    targetRevision: HEAD
    path: infrastructure/monitoring
  destination:
    server: https://kubernetes.default.svc
    # ConfigMaps are in different namespaces, so we let Kustomize/Argo handle namespace matching or use a generic destination.
    # Namespace here is just for the Application CR location.
    namespace: openshift-monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
