apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mailrise
  namespace: openshift-gitops
spec:
  destination:
    namespace: media-stack
    server: https://kubernetes.default.svc
  project: default
  source:
    path: apps/mailrise/overlays/prod
    repoURL: https://github.com/sigtom/wow-ocp.git
    targetRevision: feature/add-apprise-mailrise
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true