apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plex
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/sigtom/wow-ocp.git
    targetRevision: feature/sidecar-migration
    path: apps/plex/base
  destination:
    server: https://kubernetes.default.svc
    namespace: media-stack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
