apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: aap-infra-login
  namespace: ansible-automation-platform
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-login
    kind: ClusterSecretStore
  target:
    name: aap-infra-creds-secret
    creationPolicy: Merge
    deletionPolicy: Retain
  data:
  - secretKey: proxmox_user
    remoteRef:
      key: proxmox-api
      property: username
  - secretKey: proxmox_token_secret
    remoteRef:
      key: proxmox-api
      property: password

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: aap-infra-fields
  namespace: ansible-automation-platform
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-fields
    kind: ClusterSecretStore
  target:
    name: aap-infra-creds-secret
    creationPolicy: Merge
    deletionPolicy: Retain
  data:
  - secretKey: proxmox_token_id
    remoteRef:
      key: proxmox-api
      property: token_id
  - secretKey: cloudflare_token
    remoteRef:
      key: cloudflare-api
      property: token
  - secretKey: ssh_private_key
    remoteRef:
      key: aap-ssh
      property: private_key
