apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: aap-infra-login
  namespace: ansible-automation-platform
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-login
    kind: ClusterSecretStore
  target:
    name: aap-infra-creds-secret
    creationPolicy: Merge
    deletionPolicy: Retain
  data:
  - secretKey: proxmox_user
    remoteRef:
      key: proxmox-api
      property: username
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
  - secretKey: proxmox_token_secret
    remoteRef:
      key: proxmox-api
      property: password
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
  - secretKey: nautobot_api_token
    remoteRef:
      key: nautobot-api-key
      property: password
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: aap-infra-fields
  namespace: ansible-automation-platform
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-fields
    kind: ClusterSecretStore
  target:
    name: aap-infra-creds-secret
    creationPolicy: Merge
    deletionPolicy: Retain
  data:
  - secretKey: proxmox_token_id
    remoteRef:
      key: proxmox-api
      property: token_id
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
  - secretKey: cloudflare_token
    remoteRef:
      key: cloudflare-api
      property: token
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
  - secretKey: ssh_private_key
    remoteRef:
      key: aap-ssh
      property: private_key
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
  - secretKey: github_pat
    remoteRef:
      key: aap-secrets
      property: github_pat
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
  - secretKey: RHSM_ACTIVATION_KEY
    remoteRef:
      key: rhsm-activation
      property: rhsm_activation_key
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
  - secretKey: RHSM_ORG_ID
    remoteRef:
      key: rhsm-activation
      property: rhsm_org_id
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
