apiVersion: batch/v1
kind: Job
metadata:
  name: aap-seeder
  namespace: ansible-automation-platform
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: seeder
          image: image-registry.openshift-image-registry.svc:5000/ansible-automation-platform/custom-homelab-ee:latest
          imagePullPolicy: Always
          command: ["/bin/bash", "-c"]
          args:
            - |
              set -e
              export HOME=/tmp
              
              # Fix UID lookup for OpenShift
              if ! whoami &> /dev/null; then
                if [ -w /etc/passwd ]; then
                  echo "default:x:$(id -u):0:default user:${HOME}:/bin/bash" >> /etc/passwd
                else
                  echo "WARNING: /etc/passwd is not writable, git might fail."
                fi
              fi
              
              echo "----------------------------------------"
              echo "AAP Seeder Job Starting (User: $(whoami))"
              echo "----------------------------------------"
              
              echo "1. Configuring SSH..."
              mkdir -p ~/.ssh
              echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
              chmod 600 ~/.ssh/id_rsa
              ssh-keyscan github.com >> ~/.ssh/known_hosts
              
              export GIT_SSH_COMMAND='ssh -i /tmp/.ssh/id_rsa -o UserKnownHostsFile=/tmp/.ssh/known_hosts'
              
              echo "2. Cloning Repository..."
              rm -rf /tmp/repo
              # Verify connectivity first
              ssh -i /tmp/.ssh/id_rsa -o UserKnownHostsFile=/tmp/.ssh/known_hosts -T git@github.com || true
              
              git clone git@github.com:sigtom/wow-ocp.git /tmp/repo
              
              echo "3. Running Configuration Playbook..."
              cd /tmp/repo
              ansible-playbook automation/aap-config/setup-aap.yml -v
          env:
            - name: CONTROLLER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: aap-controller-secrets
                  key: password
            - name: SSH_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: aap-infra-creds-secret
                  key: ssh_private_key
            - name: PROXMOX_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: aap-infra-creds-secret
                  key: proxmox_token_secret
            - name: PROXMOX_TOKEN_ID
              valueFrom:
                secretKeyRef:
                  name: aap-infra-creds-secret
                  key: proxmox_token_id
            - name: PROXMOX_USER
              valueFrom:
                secretKeyRef:
                  name: aap-infra-creds-secret
                  key: proxmox_user
            - name: CLOUDFLARE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: aap-infra-creds-secret
                  key: cloudflare_token
