apiVersion: v1
kind: LimitRange
metadata:
  name: media-stack-limits
  namespace: media-stack
spec:
  limits:
  - default:
      cpu: "500m"
      memory: "1Gi"
    defaultRequest:
      cpu: "100m"
      memory: "256Mi"
    type: Container
