apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-library-pvc
  namespace: media-stack
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8000Gi
  storageClassName: truenas-nfs
  volumeName: media-library-pv
