---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: real-debrid-api
  namespace: media-stack
spec:
  encryptedData:
    token: AgBAvtmh5imFVNMYblWmnoZzGvnDtGlPvA92Jeb7yRQTKiEkz0c6YUtAYOtVeyX68wHrfTLQdVO+F1h/uMpUbNBa3Y+1V87Gv8KlvUMpRVnB9l2cX9KJUsDp3gFfuFMKcwh8KqB3PxQ3MZC2HBxNXAolnNkl6mRUKlgAfdcv8k2c7wWdYubGuDKui92V8yKOZBaCiZYbsXrMrW6TAPLBU8qmeobGwtO8RzEe0e8XxAjDCnGrrxBJYzo1E8yHqSVWTkdEHlHWCePB2j7cX+djfoxHuXnjeHTgCLhm07HvxpBtCf2MCSaaU2L+eYVGQDbMAB0KJqWwUF+Yroy9HwUTKMWeg8VI3ieOlX2Y6EsUUH9mVAUjD3oWsr6GflNJapx0R7x+5C0qtMR0CMqOT8CWMP2Cb83OmMgVh4rfZoC14CJohf1syLV+zocPoNnVBrApzdE4RB4Mts4td+fYPyPiBbhC1CyUUqAp+iKgvms2bmYGboBTK/ZARyC9yRIkoMZ0pTJt9YY4JimKQpTAsExlLUSjtWG4Ykj1mHxvZRZCJxbkKCwGcgwoYd5qrp9uJLfGInfP8fB7UBRlda4S0A6z5aoT/qodVDJZkIqZDu5yJmQ1qLZ8deRHDE7qbjX+gzMOd1CjBXFWsJAlPLGmNjdAQ5aLnBgey5AwMoD4JInBARkmwzNcorzBBdy1QnoWVKvLHSheEKRlwTLKbNMaVM9wH7DQr8ZwZbDCP2WWh1w+JsbBSOmlmmLv833mDbPtRr/cNqBfuZJb
  template:
    metadata:
      name: real-debrid-api
      namespace: media-stack
