apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rclone-config
  namespace: media-stack
spec:
  encryptedData:
    rclone.conf: AgA...PLACEHOLDER...
  template:
    metadata:
      name: rclone-config
      namespace: media-stack
    type: Opaque