apiVersion: batch/v1
kind: Job
metadata:
  name: verify-media-mount
  namespace: media-stack
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  ttlSecondsAfterFinished: 600
  template:
    spec:
      containers:
      - name: test
        image: alpine:latest
        command: ["/bin/sh", "-c", "echo 'GitOps Verify $(date)' >> /mnt/media/gitops_verify.log && ls -l /mnt/media/gitops_verify.log && echo 'Verification Successful. Sleeping 60s...' && sleep 60"]
        volumeMounts:
        - mountPath: "/mnt/media"
          name: media
      volumes:
      - name: media
        persistentVolumeClaim:
          claimName: media-library-pvc
      restartPolicy: Never
