apiVersion: nfd.openshift.io/v1
kind: NodeFeatureDiscovery
metadata:
  annotations: {}
  finalizers:
    - nfd-finalizer
  name: nfd-instance
  namespace: openshift-nfd
spec:
  enableTaints: false
  instance: ""
  prunerOnDelete: false
  topologyUpdater: false
  workerConfig:
    configData: |
      core:
        sleepInterval: 60s
      sources:
        pci:
          deviceClassWhitelist:
          - "0200"
          - "03"
          - "12"
          deviceLabelFields:
          - "vendor"
        custom:
        - name: nvidia-gpu
        - name: amd-gpu
          labels:
            feature.node.kubernetes.io/amd-gpu: "true"
          matchAny:
          - matchFeatures:
            - feature: pci.device
              matchExpressions:
                vendor:
                  op: In
                  value:
                  - "1002"
                device:
                  op: In
                  value:
                  - "74a0" # MI300A
                  - "74a1" # MI300X
                  - "740f" # MI210
                  - "7408" # MI250X
                  - "740c" # MI250/MI250X
                  - "738c" # MI100
                  - "738e" # MI100
