apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    olm.providedAPIs: NodeFeature.v1alpha1.nfd.k8s-sigs.io,NodeFeature.v1alpha1.nfd.openshift.io,NodeFeatureDiscovery.v1.nfd.openshift.io,NodeFeatureGroup.v1alpha1.nfd.k8s-sigs.io,NodeFeatureRule.v1alpha1.nfd.k8s-sigs.io,NodeFeatureRule.v1alpha1.nfd.openshift.io
  name: openshift-nfd
  namespace: openshift-nfd
spec:
  targetNamespaces:
    - openshift-nfd
  upgradeStrategy: Default
