# RBAC for OpenShift Logging Console integration and Collector permissions
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: logging-collector-prowl
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-logging-collector
subjects:
- kind: ServiceAccount
  name: log-collector
  namespace: openshift-logging
