apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
    - name: local-users
      mappingMethod: claim
      type: HTPasswd
      htpasswd:
        fileData:
          name: local-users
    - name: onelogin
      mappingMethod: claim
      type: OpenID
      openID:
        clientID: 389bbe10-fc73-013d-efa8-6773d26b29b1142641
        clientSecret:
          name: onelogin-client-secret
        claims:
          preferredUsername:
            - preferred_username
          name:
            - name
          email:
            - email
          groups:
            - Groups
        issuer: https://sigtom.onelogin.com/oidc/2
