apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: workload-br130
  namespace: technitium-dns
spec:
  config: '{
      "cniVersion": "0.3.1",
      "name": "workload-br130",
      "type": "bridge",
      "bridge": "br130",
      "ipam": {}
    }'
