apiVersion: v1
kind: Namespace
metadata:
  name: technitium-dns
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: technitium-dns-quota
  namespace: technitium-dns
spec:
  hard:
    requests.cpu: "500m"
    requests.memory: "1Gi"
    limits.cpu: "1"
    limits.memory: "2Gi"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: technitium-dns-limits
  namespace: technitium-dns
spec:
  limits:
  - default:
      cpu: 500m
      memory: 512Mi
    defaultRequest:
      cpu: 100m
      memory: 256Mi
    type: Container
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-dns-and-ui
  namespace: technitium-dns
spec:
  podSelector:
    matchLabels:
      app: technitium-dns
  policyTypes:
  - Ingress
  ingress:
  - ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53
    - protocol: TCP
      port: 5380
