apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: technitium-dns-monitor
  namespace: technitium-dns
  labels:
    app: technitium-dns
spec:
  selector:
    matchLabels:
      app: technitium-dns
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics
