apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: technitium-vm
  namespace: technitium-dns
  labels:
    app: technitium-dns
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/domain: technitium-vm
        app: technitium-dns
    spec:
      domain:
        cpu:
          cores: 2
        resources:
          requests:
            memory: 2Gi
        devices:
          disks:
            - name: rootdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
            - name: default
              bridge: {}
          rng: {}
      networks:
        - name: default
          pod: {}
      volumes:
        - name: rootdisk
          dataVolume:
            name: technitium-vm-disk
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |
              #cloud-config
              hostname: dns.sigtom.dev
              ssh_authorized_keys:
                - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEEJZzVG6rJ1TLR0LD2Rf1F/Wd6LdSEa9FoEvcdTqDRd sigtom@ilum
                - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOYsVYU0IzJ4hKNz0Hx6RwGW4wUuIPid1wJxwccp3cDT sigtom@localhost.localdomain
              user: ubuntu
              password: ubuntu
              chpasswd: { expire: False }
              ssh_pwauth: True
              network:
                version: 2
                ethernets:
                  enp1s0:
                    dhcp4: true
---
apiVersion: v1
kind: Service
metadata:
  name: technitium-vm-svc
  namespace: technitium-dns
  annotations:
    metallb.universe.tf/loadBalancerIPs: 172.16.100.210
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  selector:
    app: technitium-dns
  ports:
    - name: dns-udp
      protocol: UDP
      port: 53
      targetPort: 53
    - name: dns-tcp
      protocol: TCP
      port: 53
      targetPort: 53
    - name: http-admin
      protocol: TCP
      port: 5380
      targetPort: 5380
    - name: https-admin
      protocol: TCP
      port: 53443
      targetPort: 53443
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
    - name: cluster
      protocol: TCP
      port: 5333
      targetPort: 5333
    - name: ssh
      protocol: TCP
      port: 22
      targetPort: 22
    - name: dot
      protocol: TCP
      port: 853
      targetPort: 853
    - name: doq
      protocol: UDP
      port: 853
      targetPort: 853
    - name: dhcp-67
      protocol: UDP
      port: 67
      targetPort: 67
    - name: dhcp-68
      protocol: UDP
      port: 68
      targetPort: 68
