---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: technitium-api-token
  namespace: technitium-dns
spec:
  encryptedData:
    token: AgCrhetUIaCx3AU4aSM7SAC5MYX1kfGexqwty2yunkg1ce1NnLbvJo6MglEdsvbyyDmLTcyzfI7fcUgyhHCbcoUtlm0wWip2zKEVIn82tMyZ6jJJsBlhl3LkbkXNp5Ra9UcQtd1ofR3kJpGEwO/zXiVOPvt0N26+DATHjmTlPRB7ISHqZWTFO6uo6lXyjGBcDvbjj6SLqrfVu7dDBMORo9zN3bt/CSSszLVocm9RxHKx2Ye+6iP+hUaEpvwtgnID3ekASn/omia9oK3BZ8YP1zWPeqo4bTy6UvgpZp8kDyhAfNZbhJvPAmyepFq057xmOszIXcnRyChr8AY43QfYZYm7XvfAehELZHcLwuLMUESJNZKYX7qteQUCDSOvnUmlQ5GJycEzF2wZH44+fvfBQLeebCk8i94gmIMQJw3Ylbk19yj1CwDLetUq7FhRjv61Iw7Y7inREHCA8joCHExwTWSedQq4lLWMVZC294xpcefFMCd23LszAM4C909mjWajehwApBIf6D+q9R5CwEtwFuB3TyYU0aLJaUU3ZZtU3KCb2H+bwJjL8hsImrHwqINcybL+zRhr2r1rjLg0igg2QxUwBTtJXYkpe+xMrEiRS6Aw+M2Iq8YxWC7acbPr/6re++PXudQzbsftJUZnzjGbQJErMeTHY3NJkhr74pDLkoTYTUucmpRHdCzIclIjsaxK1zX7vpW6ikuM1yUumnZnhITi1uWs1IoTR6ejgfalShtTwY2aaJIlB3+ntSgXMrGZcevjtDG+69VqreLlptXyvgZs
  template:
    metadata:
      name: technitium-api-token
      namespace: technitium-dns
