---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgAqzle4BLpAqrk9PshYU/afTkDNzqVybYkkPa5LGzAU+uHiQmWphKY/gKnY5GmXrU94SU9MQkDm4wXDcuFJdBcQE+qlNL3kRvCMPnSLt0biXzo6Jd6ezKjwlfTQG3UY+4vNb0L2wfmHQLiH8ZVRTK+f3SMnGIdxtOagwrugaPK2HSPuLQ7VRWcCSQRKWMgoq1PFtmnAqNWAZgOfn2X3hjOZ68XkJc1USpUWt2oBM+8Y4blKrVeuSrl283g4l9H89/54CcC53ytUQYgH6ntL9runVs97+6IhPt0Q4muaH/jKyiJTu9oGO20YpSoFpqD9mRQXuheHLUPXUtKfq/Y3DXbZNMvjnmf64gnT4vjusdhhBBZBTasrhsMKCgii5ehLhCGD5kOSxnhCv9smPs2fr7gXYOdJH0HwC0do1sohEvX2sXPPtiUhPXoGPngXekGNMnLYLdZ9wd2+vBo7FfJTnQ+6OZ+/HGK8pk2oJva82oIomHY+8a3nzZOANRLAe7rxOJY87xFsMlU33iG8f8fvPa3i5cWjAMcqYWIpy6gzUhQlRppjHwHhfWna1+C57XeOpszeWbTKt06FZlmTNH9guUHg12Dn+KNMbT3DwWVc9ashliYykRvRXaTuZY2gXuTwrTH02A/Y2Bw29esa4kNf/uv4koES9q6RhoOIk+Wh8CVSQquG1VhwPinBE+cDgmYVk8Y+Z5Dn8poaViWuHSRDNLXoLS5DdxcRtQFNkVRqWXYKhVpkvyP08IvQ
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
