---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgAIGyTY5SnKXPdwQiU37/7faO9a2KG/S8Oq35GXajEatyDYXA6TJ6Cc4SJO4xXsx+i2+2K4Cds18y3H7z0ViXQI99ruJaYZtKuEe9F1Ug+Vb7OGCEUOT4lfGoVgvH86q3kCcaG/zUk+W06YIluNALgqHc/EPU4OPNhxnGXT1TKyge/4sN7wFSpLZA/z89gMISe/WD0ynfgN/GPd8s/VQWWk9dvyPi0ovyODAUR5Md9//eh/7kB6QcYrs6p7hUnQqVnblRZMrptuTdFKDvWnDZlYelwtTLTnLv2OikQubhR9MkQ6mP3N7n8P4jZcpkqQxZvzI+MpV0IVgSuZMxtEWOY32DJd/zsChFtH5u2noqD4c4QX14veEr+oj9uEW9HhAF2LD0O9NSpfj2WfSB8dQ2eVmgsrgfhDppsJm06mF9wwuQHob4/7wmacfvVVcRWA8WwTikYDO8CuScbhy/0j8nsiwnH2qSNpHbnsZCcPJKlXCZWhssXZVy7f3fdL/qpd6bejtJgy2S7EQTTPUzPentYxD9cxgMUK1pdg0OVjOHrNPoyvFZDmAsQKKAbsM6LYd2vViCiNHj5hK7+EZkEO2rYKK6x64X0yki8/sIeyHH5YSknKigN/9PXAQ1WODfVKPfHIv5Y36azZwTxYHm9KBv+eROJkuM4ZyQSlFCvvBHzNqKqes+V1JJ+YqaddsJsC4h4e9YUNspg6tEeCrE4CX43A0b25KBPBmMdxmsbsO9vPAzmtjV/+vf9F
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
