apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cloudflare-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: tec.thor@gmail.com # USER: Update this to your real email if different
    privateKeySecretRef:
      name: letsencrypt-prod-account-key
    solvers:
    - dns01:
        cloudflare:
          email: tec.thor@gmail.com # USER: Update this to your Cloudflare login
          apiTokenSecretRef:
            name: cloudflare-api-token
            key: api-token
