---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vaultwarden-admin-token
  namespace: vaultwarden
spec:
  encryptedData:
    token: AgDQQHN7Xt52ee7IJjRbFnKExmc4cH80HlpKYyzHJGbVHQYSih2ugx0QOni9JTHh8R9IfgRGxP9zD0NImbQbYDU5KF79KLFwHZBJbCm+OLmN531mItV2i7rN4F/aE+e8PD/zn8M4dXjSx0/k4aqV8kNMaMNKsrGWUMwVOgIS4jnOXf97Y1ecp9IY7HHClVZQlrxOkc4BoNbhP3M9KeLh83Wu4Ka6NfKbNmZ2Hn1wYv8jXVpB0kTsrtblhoV45skCCu9im8SVMx0kYowZyrTVrVeTRiIFQVb0dkZTszifWaCMy24WMOjidjxhed4WNV4hAVOLbKno5mgOSQ9FM4BdVqJKejg84l7z7ulS5U1afW43S1+W0MTj1GVJuo6OK8R7KvVQk1R8o88TbZGZQf4u7lxtPhCOb57+f8b6MymlVautxCve6RWHfF0QbKmnbEbflDY7F08m6rS7QpI+kuSjPVaZBsVod13BjQOC8ICtE7Me/N8YHeyDQ3uMijjuvYjafHKdalJZ6uKwaHa2kiJtd2EsqJnZfQAP24+T2cAKQPVIt3HUdCCXhqI7eNBJXJnREFf+1RxtkVU40YnhKphIFJo9xmQV6QxOARX6qVfHtfSmzSI7CVQYR8kRuOtzFzX3rH5a/NVNE3RFyvoEY5FtlEQlJNRfnnXR1vu6DK9U6Xmkk4XEUT3AnD9k1YBeu2meQy1SsG7sYYZmugc547gg49bkiSesVbvSRkwd1b0BFprbzrjYCy4=
  template:
    metadata:
      name: vaultwarden-admin-token
      namespace: vaultwarden
