plugin: networktocode.nautobot.inventory
api_endpoint: http://172.16.100.15:8080
validate_certs: false


# Filter for active and planned hosts
status:
  - Active
  - Planned

# Group hosts by role and location
group_by:
  - device_roles
  - locations

# Compose variables from custom fields and properties
compose:
  ansible_host: primary_ip4.address | default('') | split('/') | first
  vmid: custom_fields.proxmox_vmid | default(omit)
  proxmox_vmid: custom_fields.proxmox_vmid | default(omit)
  proxmox_node: cluster.name | default('') | replace('-cluster', '')
  proxmox_vmtype: "'qemu' if object_type == 'virtualization.virtualmachine' else 'lxc'"
  os_type: "platform.name | lower | replace(' ', '') | replace('.', '') | replace('04', '') | truncate(8, True, '')"
  ansible_user: "'root'"
  tshirt_size: custom_fields.t_shirt_size | default('medium')



  app_list: custom_fields.application_list | default([])
