# Proxmox Dynamic Inventory Configuration
# This file is used by AAP to discover LXC and VMs
plugin: community.proxmox.proxmox
url: "https://172.16.110.101:8006"
validate_certs: false

# Credentials will be injected by AAP from the "Proxmox Production" credential
# via environment variables
user: "{{ lookup('env', 'PROXMOX_USER') }}"
token_id: "{{ lookup('env', 'PROXMOX_TOKEN_ID') }}"
token_secret: "{{ lookup('env', 'PROXMOX_SRE_BOT_API_TOKEN') }}"

# Organization
want_proctitle: true
group_by_node: true
group_by_type: true

# Hostname mapping
hostnames:
  - name
