---
# Proxmox VM Deployment Playbook
# Uses existing proxmox_vm role from automation/roles/proxmox_vm/
#
# Prerequisites:
# 1. Add target VM to automation/inventory/hosts.yaml:
#    my-vm:
#      ansible_host: 172.16.110.XXX  # Free IP in VLAN 110
#      vmid: XXX                      # Unique VMID
#      proxmox_node: wow-prox1
#
# 2. Set PROXMOX_SRE_BOT_API_TOKEN environment variable:
#    export PROXMOX_SRE_BOT_API_TOKEN="your-token-here"
#
# 3. Ensure SSH key exists: ~/.ssh/id_pfsense_sre
#
# Usage:
#   cd automation
#   ansible-playbook -i inventory/hosts.yaml playbooks/deploy-my-vm.yaml

- name: Deploy Proxmox VM from Template
  hosts: my-vm  # CHANGE ME: Match host in inventory
  gather_facts: no
  
  # Optional: Override default VM resources
  # vars:
  #   vm_cores: 4
  #   vm_memory: 4096
  #   vm_disk_size: 50
  
  roles:
    - proxmox_vm

- name: Wait for VM to boot and cloud-init to complete
  hosts: my-vm  # CHANGE ME
  gather_facts: no
  tasks:
    - name: Wait for SSH to become available
      wait_for_connection:
        delay: 10
        timeout: 300
      
    - name: Wait for cloud-init to finish
      command: cloud-init status --wait
      changed_when: false

- name: Post-provisioning configuration
  hosts: my-vm  # CHANGE ME
  become: yes
  tasks:
    - name: Update package cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
    
    - name: Install essential packages
      apt:
        name:
          - vim
          - git
          - curl
          - wget
          - htop
          - net-tools
          - qemu-guest-agent
        state: present
    
    - name: Enable and start QEMU guest agent
      systemd:
        name: qemu-guest-agent
        enabled: yes
        state: started
    
    - name: Set timezone
      timezone:
        name: America/New_York
    
    - name: Set hostname
      hostname:
        name: "{{ inventory_hostname }}"
    
    - name: Configure /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: "{{ ansible_host }} {{ inventory_hostname }} {{ inventory_hostname }}.sigtomtech.com"
        state: present

# Optional: Register VM in Technitium DNS
# - name: Register VM in DNS
#   hosts: localhost
#   gather_facts: no
#   roles:
#     - role: technitium_record
#       vars:
#         dns_server: "172.16.110.211"
#         dns_zone: "sigtomtech.com"
#         dns_record: "{{ hostvars['my-vm'].inventory_hostname }}"
#         dns_record_type: "A"
#         dns_record_value: "{{ hostvars['my-vm'].ansible_host }}"

# Optional: Configure firewall
# - name: Configure UFW firewall
#   hosts: my-vm
#   become: yes
#   tasks:
#     - name: Install UFW
#       apt:
#         name: ufw
#         state: present
#     
#     - name: Allow SSH
#       ufw:
#         rule: allow
#         port: '22'
#         proto: tcp
#     
#     - name: Enable UFW
#       ufw:
#         state: enabled
#         policy: deny
