---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: apprise-config
  namespace: media-stack
spec:
  encryptedData:
    apprise.yml: AgC3MNZRr9dAsvjjFuFlfKKhX5qadkGpDoBu+FntKdXxE4Umi7u8ERRoKnQkF31tVi3hDpz2z8oq/6foprsy/uNsVDWDTTa5V+LDPSed9fS212pOd7DMJBAr5dy4SqsFAyaAProPPux+gAS1+zJiNI41MInlpZhHNr4SngJW4i1RiD771KbXHk+kWLPvP76zSwlrPkW/5TPt2PHcQhYJBEbNDHOm8k4nNTkdkqeUe3M4Xhe7fSY+WsnnuTIsriBXx7cMmJbzKzMaZa/KzSMZhorDf7ZpCyQcmshpoqgDJoYcVHQNGlyMO2kFckTffGxH/GtLvwBPi08Hutf0hMv5NVv1nrLmYD4zZHRlfWeYVAdEfaDkrbQAklsqY86ik4khYNmK8c914/QO89peXuVYoU7Bl388bI8i8HgmnqbDNN9AiBzyWqs01PUu0a1FWVEAGKI53T3uYLXCICq8OU0C0M+wylSYOkK3yjouJfbtafBF1wTpmXJO6kDWLjURMRpIJpj6rjn5ahrm33A+uSfyp0xKlltwTI6OGF2c9+Cs5k+Kn1IhM2jYfsxReeClpYpbXbSRj5QnPbnhhbgImIEu+BE7jE5uUdVt9Hi53xyEhoZ/T/zzsDcI94hMkOBg9xhn7kBApgGbcS2WLnrgl7g+C6RL9gDxQG9+XMeUJiyKoR9wLbLx1oa75YGXKB76GqzJG09QD2n2ruiUme4=
  template:
    metadata:
      name: apprise-config
      namespace: media-stack
