---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: apprise-config
  namespace: media-stack
spec:
  encryptedData:
    apprise.yml: AgBVH/yc01Webv3dysaiNBr6ckv3M3af+76pvAvmif5I+lhb0SzckmfB+g4ZYiGd1QHqojdMkBn9VMTPgd33H3YAi/S7bqhsxWG5SdXH0iJUO3TteVxIYYRFpk+0mR5s6rRqmlGH6P4nd9nOaDLBedeqjek1EM95JJIE/IjlKUyObUnu3d3bF0wcK1LwYQmUCu9S4nW3cjtR6+GmrdYjPBxZoJPraN14EIjCkyZIatcNraA+C2DQYepMoZCw4lwb0CM/5ZHt4EPon16JvPZuMdaizmqLiz4S9vq4gewYXguaTCWkKbwqXlr2qX2W+LjBEGrDGf98yu6oAQunaRRxW6BnHs4OUugJPGzwe85Snp6wJ5cWyvmIgafHGKE+ohcFuUWatebyCo6MNsbSK9FzhQCGRIA6jravccDGYVq20++mMrvTOytvsitSFlWOR41oFudKLHGEESqP+qciyNJKrTloZaBGEQLoJ+YBIMPVLoBZqSBXF9PD5hYVNz+zgKaER+gkGnObk/ozxpTSpSN3FJsEcDOYbfQOejtIXQGWj6JWY2npP0zO695QcEYgbd9hRmMITcChXxtOxNPfzieooFVQbsz/qJ4XiT+YeTe8H7jawxUOvRU+/fUbJjuRSNf5RXftmoFZpqE7M+u4eMcH+SANFGByzGSeAEavzzKQB5kWciVPEfrkmjyUZxuQQpS7XNlPJ8mrsSeuVSK90R16t5Y3KLFmz9R8Hohv8kEfEOPtTYwyMH+q5CV+mbSBz8h/UrRiK+4TNE9Vr/WtUF3z1PkBSybMKDOjijHhyvuFkw==
  template:
    metadata:
      name: apprise-config
      namespace: media-stack
