apiVersion: apps/v1
kind: Deployment
metadata:
  name: overseerr
  namespace: media-stack
  labels:
    app: overseerr
    zone: zone4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: overseerr
  template:
    metadata:
      labels:
        app: overseerr
        zone: zone4
    spec:
      serviceAccountName: discovery
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - wow-ocp-node2
                - wow-ocp-node3
      initContainers:
      - name: init-dirs
        image: docker.io/alpine:latest
        command: ["/bin/sh", "-c", "mkdir -p /mnt/media/zurg /mnt/media/torbox"]
        volumeMounts:
        - name: media-storage
          mountPath: /mnt/media
      containers:
      # Sidecar: Mount Zurg
      - name: rclone-zurg
        image: docker.io/rclone/rclone:latest
        securityContext:
          privileged: true
        args:
        - "mount"
        - "zurg:"
        - "/mnt/media/zurg"
        - "--config=/config/rclone/rclone.conf"
        - "--allow-other"
        - "--vfs-cache-mode=full"
        volumeMounts:
        - name: media-storage
          mountPath: /mnt/media
          mountPropagation: Bidirectional
        - name: rclone-zurg-config
          mountPath: /config/rclone
          readOnly: true
      # Sidecar: Mount TorBox
      - name: rclone-torbox
        image: docker.io/rclone/rclone:latest
        securityContext:
          privileged: true
        args:
        - "mount"
        - "torbox:"
        - "/mnt/media/torbox"
        - "--config=/config/rclone/rclone.conf"
        - "--allow-other"
        - "--vfs-cache-mode=full"
        volumeMounts:
        - name: media-storage
          mountPath: /mnt/media
          mountPropagation: Bidirectional
        - name: rclone-config
          mountPath: /config/rclone
          readOnly: true
      - name: overseerr
        image: sctx/overseerr:latest
        env:
        - name: LOG_LEVEL
          value: "info"
        - name: TZ
          value: "Etc/UTC"
        ports:
        - containerPort: 5055
          name: http
        volumeMounts:
        - name: media-storage
          mountPath: /config
          subPath: config/overseerr
        - name: media-storage
          mountPath: /mnt/media
          mountPropagation: HostToContainer
        readinessProbe:
          tcpSocket:
            port: 5055
          initialDelaySeconds: 10
          periodSeconds: 10
      volumes:
      - name: media-storage
        persistentVolumeClaim:
          claimName: media-library-pvc
      - name: rclone-zurg-config
        secret:
          secretName: rclone-zurg-config
      - name: rclone-config
        secret:
          secretName: rclone-config
---
apiVersion: v1
kind: Service
metadata:
  name: overseerr
  namespace: media-stack
spec:
  selector:
    app: overseerr
  ports:
    - protocol: TCP
      port: 5055
      targetPort: 5055
  type: ClusterIP