---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloud-credentials
  namespace: openshift-adp
spec:
  encryptedData:
    cloud: AgAgnuUFALgDxqUtB1BMKMzNjt5WaSqquePZy1OsT9KO9xYwzGKHCVHdCRpoDBsX+d1qPYHbCzoBsWN7vBALVyJUlTbb7OHQjwelUvI0ZmOnbZoA4NE8i3M6q9hM+oHYOpwXOwpk/Dkd4StZCEjq56ahkxNEQ9LrNTk0eEW9ErdYXEvQtExg7OKHbQapplwOAuXPf92WGyV1bmK1UTIA3+e/6tLqA+OkxluBmlMVz9yOfDWNBjiu4LtBswdW4sYSy8mAQzl+dhpf+xUEnkS3KQU/sw4MZBCTQyFERvtJLAnrfHOzWxew4rQDlF2ayFfCawHkQJVOi64u7F1cKkF1eyNUh9XFdNoaUa8W6I/rMcCwtqCNiQgvO3x/+qKWkfsLvGW4qIEYt83cCqvPZPobVtSio+iWjanB1p/O6mF3qBfmwGoejSfCin5tSSA2k5Kqwoiggh9ON6i5QPndFgBdnlppa0MNqDjS9BwZtbbTbMHa5mF1saqgkdtdnk6zvcvIpoq4XionlC5lPA6cL81Rneu1w509kL5rvtvqJkh7XPkzaZI1yXYoNrU+HGPD+5xMML7YMKppW4WJnqIM40VaeuSXEW2slZZPQDU4hNHwC2yDHD5Ca/7gnVDjrv11595sdxNH5cjnVr0Rr7Taj9UhQObjohPIlAbxlb9IJc9wEFAUYHZUQkV2/NjTtkxYN5adNAtB3+165dfo4voMlaq0K6YCT3OZ/uEd3+OlEI/AiJjQNKmgl4wCFUMQDoBu1Coa9/WkALaWJJSuYg4A98FOhA8TU4XiA0ZdhVohsS//5UAmqA==
  template:
    metadata:
      name: cloud-credentials
      namespace: openshift-adp
