apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dumb-secrets
  namespace: ansible-automation-platform
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-login
    kind: ClusterSecretStore
  target:
    name: dumb-secrets
    creationPolicy: Merge
    deletionPolicy: Retain
  data:
  - secretKey: realdebrid_api_key
    remoteRef:
      key: real-debrid-api-key
      property: password
  - secretKey: torbox_api_key
    remoteRef:
      key: torbox-api-key
      property: password
  - secretKey: riven_api_key
    remoteRef:
      key: riven-api-key
      property: password
  - secretKey: plex_token
    remoteRef:
      key: plex-api-token
      property: password
  - secretKey: overseerr_api_key
    remoteRef:
      key: overseerr-api-key
      property: password

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dumb-secrets-fields
  namespace: ansible-automation-platform
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-fields
    kind: ClusterSecretStore
  target:
    name: dumb-secrets
    creationPolicy: Merge
    deletionPolicy: Retain
  data:
  - secretKey: dumb_postgres_password
    remoteRef:
      key: dumb-secrets
      property: dumb_postgres_password
  - secretKey: dumb_pgadmin_password
    remoteRef:
      key: dumb-secrets
      property: dumb_pgadmin_password
