apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dumb-secrets
  namespace: ansible-automation-platform
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-login
    kind: ClusterSecretStore
  target:
    name: dumb-secrets
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
  - secretKey: realdebrid_api_key
    remoteRef:
      key: real-debrid-api-key
      property: password
  - secretKey: torbox_api_key
    remoteRef:
      key: torbox-api-key
      property: password
