---
- name: Configure Ansible Automation Platform (Config as Code)
  hosts: localhost
  connection: local
  gather_facts: false
  collections:
    - infra.controller_configuration

  vars:
    controller_host: "http://aap-controller-service.ansible-automation-platform.svc.cluster.local"
    # Authenticate using the admin password injected via env var
    controller_username: "admin"
    controller_password: "{{ lookup('env', 'CONTROLLER_PASSWORD') }}"
    
    # Configuration Data
    aap_organization: "Default"
    
    # Secrets injected from K8s Secret
    proxmox_url: "https://172.16.110.101:8006"
    proxmox_user: "{{ lookup('env', 'PROXMOX_USER') | default('sre-bot@pve') }}"
    proxmox_token_id: "{{ lookup('env', 'PROXMOX_TOKEN_ID') | default('sre-token') }}"
    proxmox_token_secret: "{{ lookup('env', 'PROXMOX_TOKEN_SECRET') }}"
    
    cloudflare_token: "{{ lookup('env', 'CLOUDFLARE_TOKEN') }}"
    
    ssh_private_key: "{{ lookup('env', 'SSH_PRIVATE_KEY') }}"
    
    # Image we just built
    ee_image: "image-registry.openshift-image-registry.svc:5000/ansible-automation-platform/custom-homelab-ee:latest"

  tasks:
    - name: Wait for AAP to be ready
      uri:
        url: "{{ controller_host }}/api/v2/ping/"
        method: GET
        user: "{{ controller_username }}"
        password: "{{ controller_password }}"
        force_basic_auth: yes
        validate_certs: no
      register: result
      until: result.status == 200
      retries: 60
      delay: 5

    # -------------------------------------------------------
    # 1. Credential Types
    # -------------------------------------------------------
    - name: Create Proxmox Credential Type
      ansible.controller.credential_type:
        name: "Proxmox VE"
        description: "Proxmox API Token authentication"
        kind: cloud
        inputs:
          fields:
            - id: host
              label: Proxmox Host URL
              type: string
            - id: username
              label: API User (user@realm)
              type: string
            - id: token_id
              label: Token ID
              type: string
            - id: token_secret
              label: Token Secret
              type: string
              secret: true
          required:
            - host
            - username
            - token_id
            - token_secret
        injectors:
          env:
            PROXMOX_URL: "{% raw %}{{ host }}{% endraw %}"
            PROXMOX_USER: "{% raw %}{{ username }}{% endraw %}"
            PROXMOX_TOKEN_ID: "{% raw %}{{ token_id }}{% endraw %}"
            PROXMOX_SRE_BOT_API_TOKEN: "{% raw %}{{ token_secret }}{% endraw %}"
        state: present
        controller_host: "{{ controller_host }}"
        controller_username: "{{ controller_username }}"
        controller_password: "{{ controller_password }}"
        validate_certs: no

    - name: Create Cloudflare Credential Type
      ansible.controller.credential_type:
        name: "Cloudflare API"
        description: "Cloudflare DNS API Token"
        kind: cloud
        inputs:
          fields:
            - id: api_token
              label: API Token
              type: string
              secret: true
          required:
            - api_token
        injectors:
          env:
            CF_DNS_API_TOKEN: "{% raw %}{{ api_token }}{% endraw %}"
        state: present
        controller_host: "{{ controller_host }}"
        controller_username: "{{ controller_username }}"
        controller_password: "{{ controller_password }}"
        validate_certs: no

    # -------------------------------------------------------
    # 2. Execution Environments
    # -------------------------------------------------------
    - name: Create Custom HomeLab EE
      ansible.controller.execution_environment:
        name: "HomeLab EE"
        description: "Custom EE with Proxmox, Docker, and AAP Config collections"
        image: "{{ ee_image }}"
        pull: always
        organization: "{{ aap_organization }}"
        state: present
        controller_host: "{{ controller_host }}"
        controller_username: "{{ controller_username }}"
        controller_password: "{{ controller_password }}"
        validate_certs: no

    # -------------------------------------------------------
    # 3. Credentials
    # -------------------------------------------------------
    - name: Create Proxmox Credential
      ansible.controller.credential:
        name: "Proxmox Production"
        organization: "{{ aap_organization }}"
        credential_type: "Proxmox VE"
        inputs:
          host: "{{ proxmox_url }}"
          username: "{{ proxmox_user }}"
          token_id: "{{ proxmox_token_id }}"
          token_secret: "{{ proxmox_token_secret }}"
        state: present
        controller_host: "{{ controller_host }}"
        controller_username: "{{ controller_username }}"
        controller_password: "{{ controller_password }}"
        validate_certs: no

    - name: Create Cloudflare Credential
      ansible.controller.credential:
        name: "Cloudflare DNS"
        organization: "{{ aap_organization }}"
        credential_type: "Cloudflare API"
        inputs:
          api_token: "{{ cloudflare_token }}"
        state: present
        controller_host: "{{ controller_host }}"
        controller_username: "{{ controller_username }}"
        controller_password: "{{ controller_password }}"
        validate_certs: no

    - name: Create AAP SSH Key
      ansible.controller.credential:
        name: "AAP Executor SSH"
        organization: "{{ aap_organization }}"
        credential_type: "Machine"
        inputs:
          username: "root"
          ssh_key_data: "{{ ssh_private_key }}"
        state: present
        controller_host: "{{ controller_host }}"
        controller_username: "{{ controller_username }}"
        controller_password: "{{ controller_password }}"
        validate_certs: no

    - name: Create Git Read-Only Credential
      ansible.controller.credential:
        name: "Git Read-Only"
        organization: "{{ aap_organization }}"
        credential_type: "Source Control"
        inputs:
          ssh_key_data: "{{ ssh_private_key }}" # Reusing same key for simplicity, ideally separate
          username: "git"
        state: present
        controller_host: "{{ controller_host }}"
        controller_username: "{{ controller_username }}"
        controller_password: "{{ controller_password }}"
        validate_certs: no

    # -------------------------------------------------------
    # 4. Project
    # -------------------------------------------------------
    - name: Create HomeLab Project
      ansible.controller.project:
        name: "HomeLab Ops"
        organization: "{{ aap_organization }}"
        scm_type: git
        scm_url: "git@github.com:sigtom/wow-ocp.git"
        scm_branch: "main"
        scm_clean: true
        scm_delete_on_update: true
        credential: "Git Read-Only"
        default_environment: "HomeLab EE"
        state: present
        controller_host: "{{ controller_host }}"
        controller_username: "{{ controller_username }}"
        controller_password: "{{ controller_password }}"
        validate_certs: no

    # -------------------------------------------------------
    # 5. Inventory
    # -------------------------------------------------------
    - name: Create HomeLab Inventory
      ansible.controller.inventory:
        name: "HomeLab Inventory"
        organization: "{{ aap_organization }}"
        state: present
        controller_host: "{{ controller_host }}"
        controller_username: "{{ controller_username }}"
        controller_password: "{{ controller_password }}"
        validate_certs: no

    # -------------------------------------------------------
    # 6. Job Templates
    # -------------------------------------------------------
    - name: Create Test AAP Flow Job Template
      ansible.controller.job_template:
        name: "Test AAP Flow"
        job_type: run
        organization: "{{ aap_organization }}"
        inventory: "HomeLab Inventory"
        project: "HomeLab Ops"
        playbook: "automation/playbooks/test-aap-flow.yaml"
        execution_environment: "HomeLab EE"
        state: present
        controller_host: "{{ controller_host }}"
        controller_username: "{{ controller_username }}"
        controller_password: "{{ controller_password }}"
        validate_certs: no

    - name: Create Deploy Traefik Job Template
      ansible.controller.job_template:
        name: "Deploy Traefik"
        job_type: run
        organization: "{{ aap_organization }}"
        inventory: "HomeLab Inventory"
        project: "HomeLab Ops"
        playbook: "automation/playbooks/deploy-traefik.yaml"
        execution_environment: "HomeLab EE"
        credentials:
          - "Proxmox Production"
          - "AAP Executor SSH"
          - "Cloudflare DNS"
        survey_enabled: true
        survey_spec:
          name: ""
          description: ""
          spec:
            - question_name: "Container ID"
              question_description: ""
              required: true
              type: integer
              variable: "target_vmid"
              min: 100
              max: 9999
              default: 210
            - question_name: "IP Address"
              question_description: ""
              required: true
              type: text
              variable: "target_ip"
              default: "172.16.100.10"
            - question_name: "Hostname"
              question_description: ""
              required: true
              type: text
              variable: "target_hostname"
              default: "traefik.sigtom.dev"
        extra_vars:
          vmid: "{% raw %}{{ target_vmid }}{% endraw %}"
        state: present
        controller_host: "{{ controller_host }}"
        controller_username: "{{ controller_username }}"
        controller_password: "{{ controller_password }}"
        validate_certs: no

    - name: Create Test Proxmox API Job Template
      ansible.controller.job_template:
        name: "Test Proxmox API"
        job_type: run
        organization: "{{ aap_organization }}"
        inventory: "HomeLab Inventory"
        project: "HomeLab Ops"
        playbook: "automation/playbooks/test-proxmox-api.yaml"
        execution_environment: "HomeLab EE"
        credentials:
          - "Proxmox Production"
        state: present
        controller_host: "{{ controller_host }}"
        controller_username: "{{ controller_username }}"
        controller_password: "{{ controller_password }}"
        validate_certs: no

    # -------------------------------------------------------
    # 7. Modular Job Templates for Workflow
    # -------------------------------------------------------
    
    - name: Create Validate IP Job Template
      ansible.controller.job_template:
        name: "Validate IP"
        description: "Check if IP is available (ping + rDNS)"
        job_type: run
        organization: "{{ aap_organization }}"
        inventory: "HomeLab Inventory"
        project: "HomeLab Ops"
        playbook: "automation/playbooks/validate-ip.yaml"
        execution_environment: "HomeLab EE"
        # No credentials needed - runs on localhost
        state: present
        controller_host: "{{ controller_host }}"
        controller_username: "{{ controller_username }}"
        controller_password: "{{ controller_password }}"
        validate_certs: no

    - name: Create Provision LXC Job Template
      ansible.controller.job_template:
        name: "Provision LXC"
        description: "Create LXC container on Proxmox"
        job_type: run
        organization: "{{ aap_organization }}"
        inventory: "HomeLab Inventory"
        project: "HomeLab Ops"
        playbook: "automation/playbooks/provision-lxc.yaml"
        execution_environment: "HomeLab EE"
        credentials:
          - "Proxmox Production"
        state: present
        controller_host: "{{ controller_host }}"
        controller_username: "{{ controller_username }}"
        controller_password: "{{ controller_password }}"
        validate_certs: no

    - name: Create Install Docker Job Template
      ansible.controller.job_template:
        name: "Install Docker"
        description: "Install Docker and Docker Compose on target host"
        job_type: run
        organization: "{{ aap_organization }}"
        inventory: "HomeLab Inventory"
        project: "HomeLab Ops"
        playbook: "automation/playbooks/install-docker.yaml"
        execution_environment: "HomeLab EE"
        credentials:
          - "AAP Executor SSH"
        state: present
        controller_host: "{{ controller_host }}"
        controller_username: "{{ controller_username }}"
        controller_password: "{{ controller_password }}"
        validate_certs: no

    # -------------------------------------------------------
    # 8. Workflow Template: Provision Docker LXC
    # -------------------------------------------------------
    
    - name: Create Provision Docker LXC Workflow
      ansible.controller.workflow_job_template:
        name: "Provision Docker LXC"
        description: "Complete workflow: Validate IP → Create LXC → Install Docker"
        organization: "{{ aap_organization }}"
        inventory: "HomeLab Inventory"
        survey_enabled: true
        survey_spec:
          name: "Docker LXC Parameters"
          description: "Configure the new Docker LXC container"
          spec:
            - question_name: "Container ID (VMID)"
              question_description: "Unique container ID (check Proxmox for next available)"
              required: true
              type: integer
              variable: "target_vmid"
              min: 100
              max: 9999
              default: 220
            - question_name: "IP Address"
              question_description: "IP in Apps network (172.16.100.12-49 available)"
              required: true
              type: text
              variable: "target_ip"
              default: "172.16.100.20"
            - question_name: "Hostname"
              question_description: "Container hostname"
              required: true
              type: text
              variable: "target_hostname"
              default: "docker-lxc"
            - question_name: "Size"
              question_description: "Resource allocation (T-shirt size)"
              required: true
              type: multiplechoice
              variable: "tshirt_size"
              choices:
                - "small"
                - "medium"
                - "large"
                - "xlarge"
              default: "medium"
        state: present
        controller_host: "{{ controller_host }}"
        controller_username: "{{ controller_username }}"
        controller_password: "{{ controller_password }}"
        validate_certs: no

    - name: Create Workflow Node 1 - Validate IP
      ansible.controller.workflow_job_template_node:
        workflow_job_template: "Provision Docker LXC"
        identifier: "validate_ip"
        unified_job_template: "Validate IP"
        organization: "{{ aap_organization }}"
        state: present
        controller_host: "{{ controller_host }}"
        controller_username: "{{ controller_username }}"
        controller_password: "{{ controller_password }}"
        validate_certs: no

    - name: Create Workflow Node 2 - Provision LXC
      ansible.controller.workflow_job_template_node:
        workflow_job_template: "Provision Docker LXC"
        identifier: "provision_lxc"
        unified_job_template: "Provision LXC"
        organization: "{{ aap_organization }}"
        state: present
        controller_host: "{{ controller_host }}"
        controller_username: "{{ controller_username }}"
        controller_password: "{{ controller_password }}"
        validate_certs: no

    - name: Create Workflow Node 3 - Install Docker
      ansible.controller.workflow_job_template_node:
        workflow_job_template: "Provision Docker LXC"
        identifier: "install_docker"
        unified_job_template: "Install Docker"
        organization: "{{ aap_organization }}"
        state: present
        controller_host: "{{ controller_host }}"
        controller_username: "{{ controller_username }}"
        controller_password: "{{ controller_password }}"
        validate_certs: no

    - name: Link Node 1 → Node 2 (on success)
      ansible.controller.workflow_job_template_node:
        workflow_job_template: "Provision Docker LXC"
        identifier: "validate_ip"
        success_nodes:
          - "provision_lxc"
        organization: "{{ aap_organization }}"
        state: present
        controller_host: "{{ controller_host }}"
        controller_username: "{{ controller_username }}"
        controller_password: "{{ controller_password }}"
        validate_certs: no

    - name: Link Node 2 → Node 3 (on success)
      ansible.controller.workflow_job_template_node:
        workflow_job_template: "Provision Docker LXC"
        identifier: "provision_lxc"
        success_nodes:
          - "install_docker"
        organization: "{{ aap_organization }}"
        state: present
        controller_host: "{{ controller_host }}"
        controller_username: "{{ controller_username }}"
        controller_password: "{{ controller_password }}"
        validate_certs: no
