---
- name: Configure Ansible Automation Platform (Config as Code)
  hosts: localhost
  connection: local
  gather_facts: false
  collections:
    - awx.awx
    - infra.controller_configuration

  vars:
    controller_host: "http://aap-controller-service.ansible-automation-platform.svc.cluster.local"
    controller_username: "admin"
    controller_password: "{{ lookup('env', 'CONTROLLER_PASSWORD') }}"

    # Configuration Data
    aap_organization: "Default"

    # Secrets injected from K8s Secret
    proxmox_url: "https://172.16.110.101:8006"
    proxmox_user: "{{ lookup('env', 'PROXMOX_USER') | default('sre-bot@pve') }}"
    proxmox_token_id: "{{ lookup('env', 'PROXMOX_TOKEN_ID') | default('sre-token') }}"
    proxmox_token_secret: "{{ lookup('env', 'PROXMOX_TOKEN_SECRET') }}"

    cloudflare_token: "{{ lookup('env', 'CLOUDFLARE_TOKEN') }}"
    nautobot_token: "{{ lookup('env', 'NAUTOBOT_API_TOKEN') }}"
    ssh_private_key: "{{ lookup('env', 'SSH_PRIVATE_KEY') }}"
    github_pat: "{{ lookup('env', 'GITHUB_PAT') }}"

    # DUMB Debrid secrets
    realdebrid_api_key: "{{ lookup('env', 'REALDEBRID_API_KEY') }}"
    torbox_api_key: "{{ lookup('env', 'TORBOX_API_KEY') }}"
    riven_api_key: "{{ lookup('env', 'RIVEN_API_KEY') }}"
    plex_token: "{{ lookup('env', 'PLEX_TOKEN') }}"
    overseerr_api_key: "{{ lookup('env', 'OVERSEERR_API_KEY') }}"
    dumb_postgres_password: "{{ lookup('env', 'DUMB_POSTGRES_PASSWORD') }}"
    dumb_pgadmin_password: "{{ lookup('env', 'DUMB_PGADMIN_PASSWORD') }}"

    # IdM secrets
    idm_admin_password: "{{ lookup('env', 'IDM_ADMIN_PASSWORD') }}"
    idm_dm_password: "{{ lookup('env', 'IDM_DM_PASSWORD') }}"

    # RHSM activation
    rhsm_activation_key: "{{ lookup('env', 'RHSM_ACTIVATION_KEY') }}"
    rhsm_org_id: "{{ lookup('env', 'RHSM_ORG_ID') }}"

    # Arr API keys
    sonarr_api_key: "{{ lookup('env', 'SONARR_API_KEY') }}"
    radarr_api_key: "{{ lookup('env', 'RADARR_API_KEY') }}"
    prowlarr_api_key: "{{ lookup('env', 'PROWLARR_API_KEY') }}"

    # Execution Environment
    ee_image: "image-registry.openshift-image-registry.svc:5000/ansible-automation-platform/custom-homelab-ee:latest"

  environment:
    CONTROLLER_HOST: "{{ controller_host }}"
    CONTROLLER_USERNAME: "{{ controller_username }}"
    CONTROLLER_PASSWORD: "{{ controller_password }}"
    CONTROLLER_VERIFY_SSL: "false"

  tasks:
    - name: Wait for AAP to be ready
      uri:
        url: "{{ controller_host }}/api/v2/ping/"
        method: GET
        user: "{{ controller_username }}"
        password: "{{ controller_password }}"
        force_basic_auth: yes
        validate_certs: no
      register: result
      until: result.status == 200
      retries: 60
      delay: 5

    # -------------------------------------------------------
    # 1. Credential Types
    # -------------------------------------------------------
    - name: Create Proxmox Credential Type
      awx.awx.credential_type:
        name: "Proxmox VE"
        kind: cloud
        inputs:
          fields:
            - id: host
              label: Proxmox Host URL
              type: string
            - id: username
              label: API User (user@realm)
              type: string
            - id: token_id
              label: Token ID
              type: string
            - id: token_secret
              label: Token Secret
              type: string
              secret: true
          required: [host, username, token_id, token_secret]
        injectors:
          env:
            PROXMOX_URL: "{% raw %}{{ host }}{% endraw %}"
            PROXMOX_USER: "{% raw %}{{ username }}{% endraw %}"
            PROXMOX_TOKEN_ID: "{% raw %}{{ token_id }}{% endraw %}"
            PROXMOX_SRE_BOT_API_TOKEN: "{% raw %}{{ token_secret }}{% endraw %}"
        state: present

    - name: Create Nautobot Credential Type
      awx.awx.credential_type:
        name: "Nautobot API"
        kind: cloud
        inputs:
          fields:
            - id: token
              label: API Token
              type: string
              secret: true
          required: [token]
        injectors:
          env:
            NAUTOBOT_API_TOKEN: "{% raw %}{{ token }}{% endraw %}"
            NAUTOBOT_TOKEN: "{% raw %}{{ token }}{% endraw %}"
        state: present

    - name: Create Cloudflare Credential Type
      awx.awx.credential_type:
        name: "Cloudflare API"
        kind: cloud
        inputs:
          fields:
            - id: api_token
              label: API Token
              type: string
              secret: true
          required: [api_token]
        injectors:
          env:
            CF_DNS_API_TOKEN: "{% raw %}{{ api_token }}{% endraw %}"
        state: present

    - name: Create GitHub Credential Type
      awx.awx.credential_type:
        name: "GitHub PAT"
        kind: cloud
        inputs:
          fields:
            - id: pat
              label: Personal Access Token
              type: string
              secret: true
          required: [pat]
        injectors:
          env:
            GITHUB_PAT: "{% raw %}{{ pat }}{% endraw %}"
        state: present

    - name: Create DUMB Secrets Credential Type
      awx.awx.credential_type:
        name: "DUMB Debrid Secrets"
        kind: cloud
        inputs:
          fields:
            - id: realdebrid_api_key
              label: RealDebrid API Key
              type: string
              secret: true
            - id: torbox_api_key
              label: TorBox API Key
              type: string
              secret: true
            - id: riven_api_key
              label: Riven API Key
              type: string
              secret: true
            - id: plex_token
              label: Plex API Token
              type: string
              secret: true
            - id: overseerr_api_key
              label: Overseerr API Key
              type: string
              secret: true
            - id: dumb_postgres_password
              label: DUMB Postgres Password
              type: string
              secret: true
            - id: dumb_pgadmin_password
              label: DUMB pgAdmin Password
              type: string
              secret: true
          required: [realdebrid_api_key, torbox_api_key]
        injectors:
          extra_vars:
            realdebrid_api_key: "{% raw %}{{ realdebrid_api_key }}{% endraw %}"
            torbox_api_key: "{% raw %}{{ torbox_api_key }}{% endraw %}"
            riven_api_key: "{% raw %}{{ riven_api_key }}{% endraw %}"
            plex_token: "{% raw %}{{ plex_token }}{% endraw %}"
            overseerr_api_key: "{% raw %}{{ overseerr_api_key }}{% endraw %}"
            dumb_postgres_password: "{% raw %}{{ dumb_postgres_password }}{% endraw %}"
            dumb_pgadmin_password: "{% raw %}{{ dumb_pgadmin_password }}{% endraw %}"
        state: present

    - name: Create IdM Secrets Credential Type
      awx.awx.credential_type:
        name: "IdM Secrets"
        kind: cloud
        inputs:
          fields:
            - id: idm_admin_password
              label: IdM Admin Password
              type: string
              secret: true
            - id: idm_dm_password
              label: IdM Directory Manager Password
              type: string
              secret: true
          required: [idm_admin_password, idm_dm_password]
        injectors:
          extra_vars:
            idm_admin_password: "{% raw %}{{ idm_admin_password }}{% endraw %}"
            idm_dm_password: "{% raw %}{{ idm_dm_password }}{% endraw %}"
        state: present

    - name: Create RHSM Activation Credential Type
      awx.awx.credential_type:
        name: "RHSM Activation"
        kind: cloud
        inputs:
          fields:
            - id: activation_key
              label: RHSM Activation Key
              type: string
              secret: true
            - id: org_id
              label: RHSM Organization ID
              type: string
              secret: true
          required: [activation_key, org_id]
        injectors:
          env:
            RHSM_ACTIVATION_KEY: "{% raw %}{{ activation_key }}{% endraw %}"
            RHSM_ORG_ID: "{% raw %}{{ org_id }}{% endraw %}"
        state: present

    - name: Create Media Arr Secrets Credential Type
      awx.awx.credential_type:
        name: "Media Arr API Keys"
        kind: cloud
        inputs:
          fields:
            - id: sonarr_api_key
              label: Sonarr API Key
              type: string
              secret: true
            - id: radarr_api_key
              label: Radarr API Key
              type: string
              secret: true
            - id: prowlarr_api_key
              label: Prowlarr API Key
              type: string
              secret: true
          required: [sonarr_api_key, radarr_api_key, prowlarr_api_key]
        injectors:
          extra_vars:
            sonarr_api_key: "{% raw %}{{ sonarr_api_key }}{% endraw %}"
            radarr_api_key: "{% raw %}{{ radarr_api_key }}{% endraw %}"
            prowlarr_api_key: "{% raw %}{{ prowlarr_api_key }}{% endraw %}"
        state: present

    # -------------------------------------------------------
    # 2. Execution Environments
    # -------------------------------------------------------
    - name: Create Custom HomeLab EE
      awx.awx.execution_environment:
        name: "HomeLab EE"
        image: "{{ ee_image }}"
        pull: always
        organization: "{{ aap_organization }}"
        state: present

    # -------------------------------------------------------
    # 3. Credentials
    # -------------------------------------------------------
    - name: Create Proxmox Credential
      awx.awx.credential:
        name: "Proxmox Production"
        organization: "{{ aap_organization }}"
        credential_type: "Proxmox VE"
        inputs:
          host: "{{ proxmox_url }}"
          username: "{{ proxmox_user }}"
          token_id: "{{ proxmox_token_id }}"
          token_secret: "{{ proxmox_token_secret }}"
        state: present

    - name: Create Nautobot Credential
      awx.awx.credential:
        name: "Nautobot API"
        organization: "{{ aap_organization }}"
        credential_type: "Nautobot API"
        inputs:
          token: "{{ nautobot_token }}"
        state: present

    - name: Create Cloudflare Credential
      awx.awx.credential:
        name: "Cloudflare DNS"
        organization: "{{ aap_organization }}"
        credential_type: "Cloudflare API"
        inputs:
          api_token: "{{ cloudflare_token }}"
        state: present

    - name: Create GitHub Credential
      awx.awx.credential:
        name: "GitHub Token"
        organization: "{{ aap_organization }}"
        credential_type: "GitHub PAT"
        inputs:
          pat: "{{ github_pat }}"
        state: present
      when: github_pat != ''

    - name: Create AAP SSH Key
      awx.awx.credential:
        name: "AAP Executor SSH"
        organization: "{{ aap_organization }}"
        credential_type: "Machine"
        inputs:
          username: "root"
          ssh_key_data: "{{ ssh_private_key }}"
        state: present

    - name: Create Git Read-Only Credential
      awx.awx.credential:
        name: "Git Read-Only"
        organization: "{{ aap_organization }}"
        credential_type: "Source Control"
        inputs:
          ssh_key_data: "{{ ssh_private_key }}"
          username: "git"
        state: present

    - name: Create DUMB Secrets Credential
      awx.awx.credential:
        name: "DUMB Debrid Secrets"
        organization: "{{ aap_organization }}"
        credential_type: "DUMB Debrid Secrets"
        inputs:
          realdebrid_api_key: "{{ realdebrid_api_key }}"
          torbox_api_key: "{{ torbox_api_key }}"
          riven_api_key: "{{ riven_api_key }}"
          plex_token: "{{ plex_token }}"
          overseerr_api_key: "{{ overseerr_api_key }}"
          dumb_postgres_password: "{{ dumb_postgres_password }}"
          dumb_pgadmin_password: "{{ dumb_pgadmin_password }}"
        state: present
      when: realdebrid_api_key != ''

    - name: Create Media Arr Secrets Credential
      awx.awx.credential:
        name: "Media Arr API Keys"
        organization: "{{ aap_organization }}"
        credential_type: "Media Arr API Keys"
        inputs:
          sonarr_api_key: "{{ sonarr_api_key }}"
          radarr_api_key: "{{ radarr_api_key }}"
          prowlarr_api_key: "{{ prowlarr_api_key }}"
        state: present
      when: sonarr_api_key != ''

    - name: Create IdM Secrets Credential
      awx.awx.credential:
        name: "IdM Secrets"
        organization: "{{ aap_organization }}"
        credential_type: "IdM Secrets"
        inputs:
          idm_admin_password: "{{ idm_admin_password }}"
          idm_dm_password: "{{ idm_dm_password }}"
        state: present
      when: idm_admin_password != '' and idm_dm_password != ''

    - name: Create RHSM Activation Credential
      awx.awx.credential:
        name: "RHSM Activation"
        organization: "{{ aap_organization }}"
        credential_type: "RHSM Activation"
        inputs:
          activation_key: "{{ rhsm_activation_key }}"
          org_id: "{{ rhsm_org_id }}"
        state: present
      when: rhsm_activation_key != '' and rhsm_org_id != ''

    # -------------------------------------------------------
    # 4. Project
    # -------------------------------------------------------
    - name: Create HomeLab Project
      awx.awx.project:
        name: "HomeLab Ops"
        organization: "{{ aap_organization }}"
        scm_type: git
        scm_url: "ssh://git@ssh.github.com:443/sigtom/wow-ocp.git"
        scm_branch: "main"
        scm_clean: true
        scm_delete_on_update: true
        credential: "Git Read-Only"
        default_environment: "HomeLab EE"
        wait: yes
        state: present

    - name: Force Project Sync
      awx.awx.project_update:
        project: "HomeLab Ops"
        wait: yes

    # -------------------------------------------------------
    # 5. Inventory
    # -------------------------------------------------------
    - name: Create HomeLab Inventory
      awx.awx.inventory:
        name: "HomeLab Inventory"
        organization: "{{ aap_organization }}"
        state: present

    - name: Create Nautobot Inventory Source
      awx.awx.inventory_source:
        name: "Nautobot Dynamic Sync"
        inventory: "HomeLab Inventory"
        source: "scm"
        source_project: "HomeLab Ops"
        source_path: "automation/inventory/nautobot.yml"
        credential: "Nautobot API"
        overwrite: true
        update_on_launch: true
        execution_environment: "HomeLab EE"
        state: present

    # -------------------------------------------------------
    # 6. Job Templates
    # -------------------------------------------------------
    - name: Create Master Deploy Job Template
      awx.awx.job_template:
        name: "Master Deploy"
        description: "Deploy/Reconcile Host and Applications from Nautobot metadata"
        job_type: run
        organization: "{{ aap_organization }}"
        inventory: "HomeLab Inventory"
        project: "HomeLab Ops"
        playbook: "automation/playbooks/master-deploy.yaml"
        execution_environment: "HomeLab EE"
        credentials:
          - "Proxmox Production"
          - "AAP Executor SSH"
          - "Cloudflare DNS"
          - "DUMB Debrid Secrets"
          - "Media Arr API Keys"
          - "GitHub Token"
          - "RHSM Activation"
        state: present

    - name: Create Sync DNS Job Template
      awx.awx.job_template:
        name: "Maintenance - Sync DNS"
        job_type: run
        organization: "{{ aap_organization }}"
        inventory: "HomeLab Inventory"
        project: "HomeLab Ops"
        playbook: "automation/playbooks/sync-pihole-dns.yaml"
        execution_environment: "HomeLab EE"
        credentials:
          - "Pi-hole API Keys"
        state: present

    - name: Create Setup Proxmox NFS Job Template
      awx.awx.job_template:
        name: "Infra - Setup Proxmox NFS"
        job_type: run
        organization: "{{ aap_organization }}"
        inventory: "HomeLab Inventory"
        project: "HomeLab Ops"
        playbook: "automation/playbooks/setup-proxmox-nfs.yaml"
        execution_environment: "HomeLab EE"
        credentials: ["AAP Executor SSH"]
        state: present

    - name: Create SSH Bootstrap Job Template
      awx.awx.job_template:
        name: "Util - SSH Bootstrap"
        job_type: run
        organization: "{{ aap_organization }}"
        inventory: "HomeLab Inventory"
        project: "HomeLab Ops"
        playbook: "automation/playbooks/util-ssh-bootstrap.yaml"
        execution_environment: "HomeLab EE"
        credentials: ["AAP Executor SSH", "Proxmox Production"]
        survey_enabled: true
        survey_spec:
          name: ""
          description: ""
          spec:
            - question_name: "Target IP (Override)"
              variable: "target_ip"
              type: text
              default: ""
              required: false
            - question_name: "Force Bootstrap Mode"
              variable: "bootstrap_mode"
              type: multiplechoice
              choices: ["true", "false"]
              default: "false"
              required: true
        state: present

    - name: Create Deploy Red Hat IdM Job Template
      awx.awx.job_template:
        name: "Deploy Red Hat IdM"
        description: "Provision and configure the IdM VM"
        job_type: run
        organization: "{{ aap_organization }}"
        inventory: "HomeLab Inventory"
        project: "HomeLab Ops"
        playbook: "automation/playbooks/identity/deploy-idm.yaml"
        execution_environment: "HomeLab EE"
        ask_limit_on_launch: true
        credentials:
          - "Proxmox Production"
          - "AAP Executor SSH"
          - "IdM Secrets"
          - "RHSM Activation"
          - "Nautobot API"
          - "Cloudflare DNS"
        state: present

    # -------------------------------------------------------
    # 7. Cleanup Redundant Templates
    # -------------------------------------------------------
    - name: Delete redundant Job Templates
      awx.awx.job_template:
        name: "{{ item }}"
        state: absent
      loop:
        - "Provision LXC"
        - "Provision Media LXC"
        - "Install Docker"
        - "Deploy Traefik"
        - "Deploy DUMB"
        - "Deploy Downloaders"
        - "Debug Traefik"
        - "Test AAP Flow"
        - "Validate IP"

    - name: Delete redundant Workflow Templates
      awx.awx.workflow_job_template:
        name: "Provision Media Docker LXC"
        state: absent

    - name: Delete redundant Inventory Sources
      awx.awx.inventory_source:
        name: "Proxmox Dynamic Sync"
        inventory: "HomeLab Inventory"
        state: absent
