#!/bin/bash
# Capacity Report - Generate comprehensive monthly capacity report

set -euo pipefail

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
BLUE='\033[0;34m'; BOLD='\033[1m'; NC='\033[0m'

MARKDOWN=false
if [[ "${1:-}" == "--markdown" ]]; then
    MARKDOWN=true
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPORT_DATE=$(date '+%Y-%m-%d')
REPORT_MONTH=$(date '+%B %Y')

main() {
    if [[ "$MARKDOWN" == "true" ]]; then
        generate_markdown_report
    else
        generate_text_report
    fi
}

generate_text_report() {
    cat <<EOF
╔══════════════════════════════════════════════════════════════════════╗
║           HOMELAB CAPACITY PLANNING REPORT                          ║
║           Date: $REPORT_DATE                                        
║           Period: $REPORT_MONTH                                     
╚══════════════════════════════════════════════════════════════════════╝

═══════════════════════════════════════════════════════════════════════
                        EXECUTIVE SUMMARY
═══════════════════════════════════════════════════════════════════════

EOF
    
    # Run cluster capacity check
    echo "OpenShift Cluster Status:"
    $SCRIPT_DIR/cluster-capacity.sh 2>/dev/null | grep -A 20 "Cluster Overview" || echo "  Data unavailable"
    echo ""
    
    echo "Proxmox Host Status:"
    $SCRIPT_DIR/proxmox-capacity.sh 2>/dev/null | grep -A 10 "Capacity Summary" || echo "  Data unavailable"
    echo ""
    
    cat <<EOF
═══════════════════════════════════════════════════════════════════════
                    COMPUTE UTILIZATION (OpenShift)
═══════════════════════════════════════════════════════════════════════

EOF
    
    $SCRIPT_DIR/node-utilization.sh 2>/dev/null || echo "Node utilization data unavailable"
    echo ""
    
    cat <<EOF
═══════════════════════════════════════════════════════════════════════
                    STORAGE UTILIZATION
═══════════════════════════════════════════════════════════════════════

EOF
    
    $SCRIPT_DIR/storage-capacity.sh 2>/dev/null || echo "Storage data unavailable"
    echo ""
    
    cat <<EOF
═══════════════════════════════════════════════════════════════════════
                    TOP RESOURCE CONSUMERS
═══════════════════════════════════════════════════════════════════════

EOF
    
    $SCRIPT_DIR/top-consumers.sh 2>/dev/null || echo "Consumer data unavailable"
    echo ""
    
    cat <<EOF
═══════════════════════════════════════════════════════════════════════
                    RECOMMENDATIONS
═══════════════════════════════════════════════════════════════════════

Based on current utilization:

1. IMMEDIATE ACTIONS (if any RED thresholds):
   - Review critical capacity alerts
   - Scale down or remove non-critical workloads
   - Block new deployments until <90%

2. SHORT-TERM (if YELLOW thresholds):
   - Identify optimization opportunities
   - Rightsize over-provisioned workloads
   - Clean up unused PVCs and resources

3. LONG-TERM PLANNING:
   - Monitor growth trends
   - Plan hardware expansion if sustained >80%
   - Budget for additional nodes or storage

═══════════════════════════════════════════════════════════════════════
                    CAPACITY FORECAST
═══════════════════════════════════════════════════════════════════════

Estimated time to reach thresholds (based on current trends):

Note: Manual analysis required for accurate forecasting.
Factors to consider:
- Current growth rate (compare to last month)
- Planned deployments
- Seasonal variations

Recommendation: Review capacity monthly and adjust forecasts.

═══════════════════════════════════════════════════════════════════════
                    REPORT METADATA
═══════════════════════════════════════════════════════════════════════

Generated: $(date '+%Y-%m-%d %H:%M:%S %Z')
Generated by: $(whoami)@$(hostname)
Report period: $REPORT_MONTH
Scripts location: $SCRIPT_DIR

Next review: $(date -d "+1 month" '+%Y-%m-%d')

═══════════════════════════════════════════════════════════════════════
EOF
}

generate_markdown_report() {
    cat <<EOF
# Homelab Capacity Planning Report
**Date:** $REPORT_DATE  
**Period:** $REPORT_MONTH

---

## Executive Summary

### OpenShift Cluster Status

\`\`\`
EOF
    $SCRIPT_DIR/cluster-capacity.sh 2>/dev/null | grep -A 20 "Cluster Overview" || echo "Data unavailable"
    cat <<EOF
\`\`\`

### Proxmox Host Status

\`\`\`
EOF
    $SCRIPT_DIR/proxmox-capacity.sh 2>/dev/null | grep -A 10 "Capacity Summary" || echo "Data unavailable"
    cat <<EOF
\`\`\`

---

## Compute Utilization (OpenShift)

### Per-Node Breakdown

\`\`\`
EOF
    $SCRIPT_DIR/node-utilization.sh 2>/dev/null || echo "Node utilization data unavailable"
    cat <<EOF
\`\`\`

---

## Storage Utilization

\`\`\`
EOF
    $SCRIPT_DIR/storage-capacity.sh 2>/dev/null || echo "Storage data unavailable"
    cat <<EOF
\`\`\`

---

## Top Resource Consumers

\`\`\`
EOF
    $SCRIPT_DIR/top-consumers.sh 2>/dev/null || echo "Consumer data unavailable"
    cat <<EOF
\`\`\`

---

## Recommendations

Based on current utilization:

### Immediate Actions (if any RED thresholds)
- Review critical capacity alerts
- Scale down or remove non-critical workloads
- Block new deployments until <90%

### Short-Term (if YELLOW thresholds)
- Identify optimization opportunities
- Rightsize over-provisioned workloads
- Clean up unused PVCs and resources

### Long-Term Planning
- Monitor growth trends
- Plan hardware expansion if sustained >80%
- Budget for additional nodes or storage

---

## Capacity Forecast

**Note:** Manual analysis required for accurate forecasting.

Factors to consider:
- Current growth rate (compare to last month)
- Planned deployments
- Seasonal variations

**Recommendation:** Review capacity monthly and adjust forecasts.

---

## Report Metadata

- **Generated:** $(date '+%Y-%m-%d %H:%M:%S %Z')
- **Generated by:** $(whoami)@$(hostname)
- **Report period:** $REPORT_MONTH
- **Scripts location:** $SCRIPT_DIR
- **Next review:** $(date -d "+1 month" '+%Y-%m-%d')

---

## Archive

Save this report to: \`/opt/capacity-reports/capacity-$REPORT_DATE.md\`

Compare to previous months:
\`\`\`bash
diff /opt/capacity-reports/capacity-2025-12-01.md /opt/capacity-reports/capacity-$REPORT_DATE.md
\`\`\`
EOF
}

main "$@"
