apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bitwarden-sdk-server-tls
  namespace: external-secrets
spec:
  secretName: bitwarden-sdk-server-tls
  issuerRef:
    name: cloudflare-prod
    kind: ClusterIssuer
  dnsNames:
    - bw-sdk.apps.ossus.sigtomtech.com
