apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: bitwarden-vault
spec:
  provider:
    bitwarden:
      auth:
        secretRef:
          clientSecret: # Name of the secret and key holding the client secret
            name: bitwarden-api-creds
            key: client_secret
          clientID: # Name of the secret and key holding the client ID
            name: bitwarden-api-creds
            key: client_id
      # Optional: custom endpoint for self-hosted Bitwarden
      # Assuming SDK Server is exposed at the same URL as Bitwarden UI
      serverURL: https://bitvault.sigtom.dev
      # To use the External Secrets SDK Server for Bitwarden
      # See: https://external-secrets.io/v0.11.0/provider-bitwarden/#bitwarden-sdk-server
      sdkServer:
        # Assuming the SDK server is accessible at the same URL as the Bitwarden instance
        # If it's a different endpoint or port, it needs to be specified here.
        # Example if SDK is on a different port: endpoint: https://bitvault.sigtom.dev:8080
        endpoint: https://bitvault.sigtom.dev
