apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: bitwarden-fields
spec:
  provider:
    webhook:
      url: "http://bitwarden-provider.external-secrets.svc.cluster.local.:8087/list/object/items?search={{ .remoteRef.key }}"
      headers:
        Content-Type: application/json
      result:
        jsonPath: "$.data.data[0].fields[?(@.name=='{{ .remoteRef.property }}')].value"
