apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: bitwarden-cloud
spec:
  provider:
    bitwarden:
      auth:
        credentials:
          secretRef:
            name: bitwarden-api-creds
            namespace: external-secrets
            client_id:
              key: client_id
            client_secret:
              key: client_secret
