apiVersion: batch/v1
kind: Job
metadata:
  name: nautobot-init
  namespace: nautobot
  labels:
    app: nautobot
    component: init
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  backoffLimit: 3
  template:
    metadata:
      labels:
        app: nautobot
        component: init
    spec:
      restartPolicy: OnFailure
      initContainers:
        - name: wait-for-postgres
          image: postgres:15-alpine
          command:
            - sh
            - -c
            - |
              until pg_isready -h nautobot-postgres -p 5432 -U nautobot; do
                echo "Waiting for PostgreSQL..."
                sleep 5
              done
              echo "PostgreSQL is ready!"
        - name: wait-for-redis
          image: redis:7-alpine
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nautobot-secrets
                  key: redis-password
          command:
            - sh
            - -c
            - |
              until redis-cli -h nautobot-redis -a "$REDIS_PASSWORD" ping | grep -q PONG; do
                echo "Waiting for Redis..."
                sleep 5
              done
              echo "Redis is ready!"
      containers:
        - name: init
          image: networktocode/nautobot:2.3-py3.11
          command:
            - sh
            - -c
            - |
              set -e
              echo "Running database migrations..."
              nautobot-server migrate --noinput
              
              echo "Creating superuser..."
              nautobot-server shell << 'PYTHON_EOF'
              from django.contrib.auth import get_user_model
              User = get_user_model()
              if not User.objects.filter(username='admin').exists():
                  User.objects.create_superuser(
                      username='admin',
                      email='sigtom@protonmail.com',
                      password='${NAUTOBOT_SUPERUSER_PASSWORD}'
                  )
                  print("Superuser created successfully")
              else:
                  print("Superuser already exists, skipping")
              PYTHON_EOF
              
              echo "Collecting static files..."
              nautobot-server collectstatic --noinput
              
              echo "Initialization complete!"
          env:
            - name: NAUTOBOT_DB_ENGINE
              value: django.db.backends.postgresql
            - name: NAUTOBOT_DB_HOST
              value: nautobot-postgres
            - name: NAUTOBOT_DB_PORT
              value: "5432"
            - name: NAUTOBOT_DB_NAME
              value: nautobot
            - name: NAUTOBOT_DB_USER
              value: nautobot
            - name: NAUTOBOT_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nautobot-secrets
                  key: postgres-password
            - name: NAUTOBOT_REDIS_HOST
              value: nautobot-redis
            - name: NAUTOBOT_REDIS_PORT
              value: "6379"
            - name: NAUTOBOT_REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nautobot-secrets
                  key: redis-password
            - name: NAUTOBOT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: nautobot-secrets
                  key: secret-key
            - name: NAUTOBOT_SUPERUSER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nautobot-secrets
                  key: superuser-password
            - name: NAUTOBOT_ALLOWED_HOSTS
              value: "*"
            - name: TZ
              value: America/New_York
          volumeMounts:
            - name: nautobot-static
              mountPath: /opt/nautobot/static
      volumes:
        - name: nautobot-static
          persistentVolumeClaim:
            claimName: nautobot-static
