apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nautobot-postgres
  namespace: nautobot
  labels:
    app: nautobot-postgres
spec:
  serviceName: nautobot-postgres
  replicas: 1
  selector:
    matchLabels:
      app: nautobot-postgres
  template:
    metadata:
      labels:
        app: nautobot-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          env:
            - name: POSTGRES_DB
              value: nautobot
            - name: POSTGRES_USER
              value: nautobot
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nautobot-secrets
                  key: postgres-password
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            - containerPort: 5432
              name: postgres
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 2Gi
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - pg_isready -U nautobot
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - pg_isready -U nautobot
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
        labels:
          app: nautobot-postgres
          velero.io/backup: "true"
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: truenas-nfs
        resources:
          requests:
            storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: nautobot-postgres
  namespace: nautobot
  labels:
    app: nautobot-postgres
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    app: nautobot-postgres
