apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-library-pv
  labels:
    type: static-nfs
spec:
  capacity:
    storage: 7300Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: truenas-nfs
  nfs:
    path: /mnt/Media/docker-media
    server: 172.16.160.100
