apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-library-pv
  labels:
    type: static-nfs
spec:
  capacity:
    storage: 11Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: truenas-nfs
  nfs:
    path: /mnt/tank/media # USER: Verify this path on TrueNAS
    server: 172.16.160.100
