apiVersion: lvm.topolvm.io/v1alpha1
kind: LVMCluster
metadata:
  name: lvmcluster-sample
  namespace: openshift-storage
spec:
  storage:
    deviceClasses:
    - deviceSelector:
        optionalPaths:
        - /dev/disk/by-path/pci-0000:02:00.0-scsi-0:0:1:0
        - /dev/disk/by-path/pci-0000:00:11.4-ata-2
      fstype: xfs
      name: vg1
      thinPoolConfig:
        chunkSizeCalculationPolicy: Static
        metadataSizeCalculationPolicy: Host
        name: thin-pool-1
        overprovisionRatio: 10
        sizePercent: 90
